# mysql
db:
  host: 127.0.0.1
  port: 3306
  user: root
  passwd: 2018
  database: ip_pool
  tablename: ip_tables

# redis
redis:
  host: 127.0.0.1
  port: 6379
  key: ip

# 是否初始化数据库
IS_INIT_DATABASE: False

# 是否开启ip验证
is_verify: True

# 验证ip url
# test_proxy_url: https://www.google.com.hk
test_proxy_url: https://cn.bing.com

user-angers:
  - {"user-agent":"Mozilla/5.0 (Linux; Android 5.1; vivo X6D Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"}
  - {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"}
  - {"User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"}
  - {"User-Agent":"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"}
  - {"User-Agent":"Mozilla/5.0 (Linux; U; Android 7.1.1; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"}
  - {"User-Agent":"Mozilla/5.0 (iPad; U; CPU OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"}
  - {"User-Agent":"com.ss.android.ugc.aweme/600 (Linux; U; Android 7.1.1; zh_CN; NX589J; Build/NMF26F; Cronet/58.0.2991.0)"}


# 日志文件配置
log_config:
  file: crawl_ip.log
  level: INFO
  pattern: '%(asctime)s - [%(filename)s:%(lineno)d] - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%m:%S'
